### ISSUE TITLE
3.2.1 no longer allow multiple Ingress classes

### ISSUE THREAD

**Issue by damacus** [bjw-s/helm-charts#331] opened 2024-06-19 15:49 UTC
# Details

- Upgraded from 3.1.0 to 3.2.1
- Use multiple Ingresses
 [example here](https://github.com/damacus/home-ops/blob/cd11f6d9d8b5c2f5fefb11f66587cf520556e0b0/kubernetes/apps/home-automation/home-assistant/app/config/values.yaml#L78-L109)

Error

```text
Error: template: app-template/templates/common.yaml:14:3: executing "app-template/templates/common.yaml" 

at <include "bjw-s.common.loader.generate" .>: error calling include: template: app-template/charts/common/templates/loader/_generate.tpl:13:6: executing "bjw-s.common.loader.generate" 

at <include "bjw-s.common.render.ingresses" .>: error calling include: template: app
template/charts/common/templates/render/_ingresses.tpl:23:10: executing "bjw-s.common.render.ingresses" 

at <include "bjw-s.common.class.ingress" (dict "rootContext" $ "object" $ingressObject)>: error calling include: template: app-template/charts/common/templates/classes/_ingress.tpl:32:34: executing "bjw-s.common.class.ingress" 

at <$value>: wrong type for value; expected string; got interface {}
```

Removing the second ingress fixes the error

**Comment by damacus** [comment] 2024-07-15 12:53
Been a bit busy with life but I've just removed the second ingress again and noticed that the ingress no longer appends -app e.g. 

- home-assistant-app
- home-assistant-internal

[See here for the flux-local diff ](https://github.com/damacus/home-ops/pull/780)

I can't see anything in the commits that would cause this though.

**Comment by bjw-s** [comment] 2024-07-29 11:56
Not really sure why that is happening in the flux-diff output. When I run your values against 3.2.1 I can see the `home-assistant-app` and `home-assistant-internal` ingresses as you would expect.

**Comment by bjw-s** [comment] 2024-10-04 13:47
Closing this one for now as I've been unable to reproduce. Feel free to comment here if it happens again and we can try to reproduce it.

**Closed by bjw-s** 2024-10-04 13:47 UTC
Labels: bug

**Comment by bjw-s** [comment] 2024-11-03 14:33
Hi @DevSecNinja, I tried to run with your values and indeed I see your error when rendering.
It is caused by https://github.com/DevSecNinja/home/blob/4b27c453ff7ce516cc2c6fc25aaed4f7fc8f0fdb/kubernetes/apps/network/adguard/app/helmrelease.yaml#L94-L95. The chart expects a string, not a `null` value. When I remove those two annotations everything works as expected.

**Comment by DevSecNinja** [comment] 2024-11-03 14:42
Ah that must be it then! But the old version worked fine with these null values. See: https://github.com/DevSecNinja/home/commit/4b27c453ff7ce516cc2c6fc25aaed4f7fc8f0fdb

Thanks for your help and the great template! I’ll try it again with 3.5.1 without the null values.
