### ISSUE TITLE
The default ingress is disabled by default - different than the docs say

### ISSUE THREAD

**Issue by mmalyska** [bjw-s/helm-charts#208] opened 2023-10-10 08:39 UTC
# Details

**What steps did you take and what happened:**

Migrate to 2.0.x and I don't have ingress enabled. Per the docs we should have it enabled by default.
```
ingress.main.enabled can be removed, since items are considered enabled by default (they can still be disabled by adding enabled: false).
```

**What did you expect to happen:**

Ingress enabled by default.

**Anything else you would like to add:**
What behaviour should be default one?

**Additional Information:**

[Place that holds error](https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml#L482)
[Place to the docs](https://github.com/bjw-s/helm-charts/blob/main/charts/other/app-template/README.md#changes-in-this-example)

**Comment by bjw-s** [comment] 2023-10-10 09:06
Thank you for raising the issue and taking the time to create the PR! This is a duplicate of #205 and the actual solution will be covered by #206. In the meantime I plan to update the docs to describe the current behavior.

**Closed by bjw-s** 2023-10-10 09:06 UTC
Labels: bug

**Comment by mmalyska** [comment] 2023-10-10 09:44
Ok, thank you for information!
